image: Visual Studio 2019

version: 3.24.{build}.0

clone_folder: c:\projects\ditto
    
install:
- set INNOSETUPPATH=C:\Program Files (x86)\Inno Setup 6
- set Path=%INNOSETUPPATH%;%PATH%
    
environment:
  VERSION_FILENAME: 3_24_%APPVEYOR_BUILD_NUMBER%_0  
  CHOCO_API_KEY:
    secure: ZeAW38gXYNcJmxTOEGhA1RC5XzmJVvxVM8bsCCARnbYHEDmtQiRZxV4G+/KY4wW9

build_script:
  - echo Building version:%appveyor_build_version%
  - cmd: nuget restore
  - echo Building 32Bit
  #- cmd: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=Win32
  #- echo Building 64Bit
  #- cmd: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=x64  

after_build:
  #- DittoSetup\rcedit-x86 Release\Ditto.exe --set-file-version %APPVEYOR_BUILD_VERSION% --set-product-version %APPVEYOR_BUILD_VERSION%
  #- DittoSetup\rcedit-x64 Release64\Ditto.exe --set-file-version %APPVEYOR_BUILD_VERSION% --set-product-version %APPVEYOR_BUILD_VERSION%
  
  #- iscc /F"DittoSetup_%VERSION_FILENAME%" "DittoSetup\DittoSetup_10.iss"
  #- iscc /F"DittoSetup_64bit_%VERSION_FILENAME%" "DittoSetup\DittoSetup_10.iss" "/dbit64=1"
  
  #- DittoSetup\BuildPortableZIP.bat "DittoPortable_%VERSION_FILENAME%" bit32
  #- DittoSetup\BuildPortableZIP.bat "DittoPortable_64bit_%VERSION_FILENAME%" bit64
  
  - ps: (Get-Content 'DittoSetup\Chocolatey\ditto.nuspec' -Raw).Replace("%version%", "$($env:APPVEYOR_BUILD_VERSION)") | Out-File 'DittoSetup\Chocolatey\ditto.nuspec'
  - copy DittoSetup\output\DittoSetup_%VERSION_FILENAME%.exe DittoSetup\Chocolatey\DittoSetup_%VERSION_FILENAME%.exe
  - copy DittoSetup\output\DittoSetup_64bit_%VERSION_FILENAME%.exe DittoSetup\Chocolatey\DittoSetup_64bit_%VERSION_FILENAME%.exe
  - cd DittoSetup\Chocolatey
  - choco pack     
  - cd ..
  - cd ..

artifacts:
  - path: DittoSetup\output\DittoSetup_%VERSION_FILENAME%.exe
    name: Ditto Setup
  - path: DittoSetup\output\DittoSetup_64bit_%VERSION_FILENAME%.exe
    name: Ditto Setup 64bit
  - path: DittoSetup\output\DittoPortable_%VERSION_FILENAME%.zip
    name: Ditto Portable
  - path: DittoSetup\output\DittoPortable_64bit_%VERSION_FILENAME%.zip
    name: Ditto Portable 64bit

